### PR TITLE
fix destructuring arguments

### PR DESCRIPTION
**Pull request by Vorobeyko**
Added parse arguments of function like:
```
({x, y}) => {}
```

Which return result.args = ` ['x', 'y']`

@tunnckoCore Can you help me with tests?

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Hi and very thanks!

And yet, I'm not sure if this case really is "args". I always wonder what to do in such complex cases. That's probably the beauty of the plugins structure.

I really want to first publish the #72 / #67  (v6 release) and then consider what to do with these cases.

For now you can literally make another plugin like the following

```js
export default () => (node, result) => {
  result.destructuredArgs = result.destructuredArgs || [];

  node.params.forEach((param) => {
    if (
      param.type === 'ObjectPattern' &&
      param.properties &&
      param.properties.length > 0
    ) {
      param.properties.forEach((prop) => {
        const { name } = prop.value;
        result.destructuredArgs.push(name);
      });
      return;
    }
  })

  return result
}
```

and if you want them all to be in `result.args` I guess you can just concat both arrays before the `return result`.

**Comment by tunnckoCore** [comment]
I update the tests, you just need to update the snapshots with Jest's `-u` flag.
Run `hela test -u` or `yarn test -u` and commit.

**Comment by tunnckoCore** [comment]
Actually, why not create a new file in `plugins/destructured-args.js` with above snippet and then update the `plugins/initial.js` to include it there like the other ones.

```diff
  import body from './body';
  import props from './props';
  import params from './params';
+ import destructured from './destructured-args';
```

and later

```diff
   result = props(app)(node, result);
   result = params(app)(node, result);
   result = body(app)(node, result);
+  result = destructured(app)(node, result);
```

But in anyway, a new published version probably won't be that soon that you may need it, so just use the above snippet.

**Comment by Vorobeyko** [comment]
Thank you!!
I will do this)

**Comment by Vorobeyko** [comment]
@Vorobeyko HI!
How can I create custom plugin and plug in it at my repository?

**Comment by Vorobeyko** [comment]
oh) I found bug on my code ) 
When I parsed class method.
```
class Obj {
  method({ locator, sec }) {}
}
```

I will fix this asap)

**Comment by Vorobeyko** [comment]
> Thank you!!
> I will do this)

I found the decide)

**Comment by tunnckoCore** [comment]
> How can I create custom plugin and plug in it at my repository?

Just get your code from here and pass it to `.use` method directly for now.

https://github.com/tunnckoCore/opensource/tree/master/@packages/parse-function#use

**Pull request closed without merging**
